name: the_ultimate_payment_processing_package
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Awaleed/the_ultimate_payment_processing_package

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.0
  collection: ^1.16.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  pretty_dio_logger: ^1.1.1
  supercharged: ^2.1.1
  webviewx: ^0.2.1

dev_dependencies:
  build_runner: null
  flutter_lints: null
  flutter_test:
    sdk: flutter
  freezed: null

flutter:
  assets:
    - assets/images/
  plugin:
    platforms:
      ios:
        pluginClass: SwiftFlutterPayPlugin
